---
title: "Data_Manipulation_D.crab"
author: "Montana McLeod"
date: "10/7/2020"
output: pdf_document
---

```{r setup, include=FALSE}
require("knitr")
opts_knit$set(root.dir = "~/Box Sync/Eder_Dungeness_2020/Model_code")
```

# Libraries 
```{r}
library(tidyverse)
library(lubridate)
library(multcomp)
require(ggplot2)

source("./Library/size.class.R")
```


# Henkel Data from 2013-2019
```{r echo=FALSE}
#Newport Data
data_N <- read.csv("../Data/Crabbing_allHenkelsizedata.csv" , stringsAsFactors = FALSE) # ./ pulls from Data folder 
data_N$Date <- as.Date( as.character(data_N$Date), format="%m/%d/%y")
# Redefining Months
data_N <- data_N %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) #Sets the Month to automatically order via month order [lubridate package]
data_N$Year <- as.numeric( format(data_N$Date, format="%Y") )
```




# Eder grant Data from 2020
## Data collected in 2020 (thru Sept 2020)
```{r}
NEW_data<-read.csv("../Data/CrabSizes2020-1.csv" , stringsAsFactors = FALSE)
colnames(NEW_data)<- c("Date","Vessel", "Pot..","Lat","Long","Depth", "Box", "BAIT","SEX","Carapace.Width","Shell.Cond","Comments", "LL1", "LL2","LL3") #rename to match previous DF for the Merge

#Fix lat errors
NEW_data$Comments <- ifelse(NEW_data$Lat == "Missing!", "Missing!", NEW_data$Comments)
NEW_data$Lat <- ifelse(NEW_data$Lat == "44.36.??", "44.36", 
                       ifelse(NEW_data$Lat == "" | NEW_data$Lat == "Missing!", NA, NEW_data$Lat) )

#Fix long errors
NEW_data$Long <- ifelse(NEW_data$Long == "-124.06.??", "-124.06", 
                        ifelse(NEW_data$Long == "", NA, NEW_data$Long) )

#ADD & Fix dates
NEW_data$Date <- as.Date(NEW_data$Date, format="%m/%d/%y")
NEW_data <- NEW_data %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) 
NEW_data$Year <- as.numeric( format(NEW_data$Date, format="%Y") )

#Fix carapace width errors
NEW_data$Carapace.Width <- as.numeric(ifelse(NEW_data$Carapace.Width == "?" | NEW_data$Carapace.Width == "", NA, NEW_data$Carapace.Width) ) 


``` 




# Final dataset/ Merge - Henkel & Eder grant datasets
```{r}
#merge the old with the new DF
Total_data_N <- merge(NEW_data, data_N, by=c("Date", "Month","Year","Carapace.Width", "Depth", "BAIT", "SEX","Pot.."), all=TRUE)
colnames(Total_data_N) <- c("Date","Month","Year","CW", "Depth", "Bait", "Sex","Pot", "Vessel", "Lat", "Long", "Box","Shell.Cond", "Comments","LL1", "LL2","LL3", "Line", "Contour")
 
#trawl df
Trawl <- subset(Total_data_N, Pot =="Trawl" | Pot == " Trawl")

#Removing Columns not interested in
Pots_N <- Total_data_N[ , c(1:4,7:8)]

#Removing trawls (Approx. 20% of the dataset)
Pots_N$Pot<- ifelse(Pots_N$Pot == "Trawl" | Pots_N$Pot == " Trawl", NA, Pots_N$Pot)   #makes Trawls NAs so it is easier to remove
Pots_N <- Pots_N[ complete.cases(Pots_N$Pot), ] # removes the NAs that are in the Pot column 
Pots_N$Pot <- as.numeric(Pots_N$Pot)
Pots_N$Sex <- as.numeric(Pots_N$Sex)

#Sort the dataframe by Month for Plot
index<- with(Pots_N, order(Year, Month, Date, Pot)) #places the order
Pots_N<- Pots_N[index,] #outputs the data in that order


#sets soaktime (emailed response from Sarah 7/13 & 8/20)
Pots_N$Soak.Time.hr <- ifelse(Pots_N$Date == "2013-12-07", 48, 
       ifelse(Pots_N$Date == "2018-06-04", 72,
       ifelse(Pots_N$Date == "2018-06-06", 48,
       ifelse(Pots_N$Date == "2018-06-08", 48, 
       ifelse(Pots_N$Date == "2020-06-10", 8,  24 ) )  ) ) )
```


# Data from the Mouth of the Columbia River from NOAA [Aug - Sept 2018]'
```{r}
#MCR data
data_MCR<-read.csv("../Data/Crabbing_data_MCR.csv", stringsAsFactors = FALSE)

data_MCR$Date <- as.Date( data_MCR$Date, format="%m/%d/%y")
data_MCR$Date[219:327] = rep("2018-09-18",109) #had to add in because in different format 
data_MCR$Date[328:363] = rep("2018-09-28",36) 

# Redefining Months / years
data_MCR <- data_MCR %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE))
data_MCR$Year <- as.numeric( format(data_MCR$Date, format="%Y") )

#Reorder df
data_MCR <- data_MCR[,c(1,10,2:9)]
colnames(data_MCR)[colnames(data_MCR) == "Carapace.Width"] <- "CW"

#Adds soak times (Email corespondance 8/20)
data_MCR$Soak.Time.hr <- ifelse(data_MCR$Date == "2018-08-23", 23, 
       ifelse(data_MCR$Date == "2018-08-30", 19,
       ifelse(data_MCR$Date == "2018-09-18", 24,
       ifelse(data_MCR$Date == "2018-09-28", 2.5,NA ) ) ) )

#save(data_MCR, Pots_N, Trawl, Total_data_N, file= "../Data/All_Dcrab.Rdata")
# save(data_MCR, file = "../Data/MCR_estuary.Rdata")
```


# Data from the Heppell's: Yaquina Bay Estuary (2003-2005)
```{r}
# Load catach and abiotic data 
  SH_catch_data <- read.csv("../Data/Estuary_Catch.csv", stringsAsFactors = FALSE)
  SH_catch_data <- subset(SH_catch_data, Common.Name == "Dungeness Crab", select = ID : Sex)
  SH_abiotic_data <- read.csv("../Data/Estuary_Data.csv", stringsAsFactors = FALSE)
  SH_abiotic_data <-SH_abiotic_data[!is.na(SH_abiotic_data$Bottom.DO.mg.l.st), ]

# Prep for loop for merge
  SH_data <- SH_catch_data
  SH_data$DO <- rep(NA, nrow(SH_data))
  trawl_id <- unique(SH_abiotic_data$ID)

# if ID matches each data set join
  for(i in trawl_id){
    DO <- SH_abiotic_data[SH_abiotic_data$ID == i, 11 ] 
    SH_data[SH_data$ID == i, 9 ] <- DO
  }

#merge created num as factors
  SH_data$Day <- as.numeric(as.character(SH_data$Day))  
  SH_data$Year <- as.numeric(as.character(SH_data$Year))
  SH_data$Length.mm <- as.numeric(SH_data$Length.mm)
  colnames(SH_data)[colnames(SH_data) == "Length.mm"] <- "CW"
  

#removes the anomaly for better viewing & ONLY males
  SH_data <- subset(SH_data, Sex == "M" & CW != 880, select = ID : Sex) #only males 


### Molt time frame
#setting up only males btw may-June 2004
  SH_data_Molt <- subset(SH_data, Month == "April"| Month ==  "September", select = ID : Sex) 
  
  End_Aug <- subset(SH_data, Month == "August" & Year != 2005, select = ID : Sex)
  SH_data_Molt <- merge(SH_data_Molt, End_Aug, by= c("ID", "Month", "Day", "Year", "Site", "Common.Name", "CW", "Sex"), all= TRUE)

#Sort the dataframe by Month for Plot
  index<- with(SH_data, order(Year, Month)) #places the order
  SH_data <- SH_data[index,]

# sub-adult Males 
Sub_males_Estr <- size.class(SH_data, NA, "sub")

# save(Sub_males_Estr, SH_data, SH_data_Molt, file= "../Data/Yaquina_data.Rdata")
```

# MCR daaset Beach Seine [2002-2008]
```{r}
setwd("~/Box Sync/McLeod_thesis/Data")

MCR_Seine <- read.csv("../Data/MCR_Seine.csv", stringsAsFactors = FALSE)

# Redefining Dates
MCR_Seine$Date <- as.Date( as.character(MCR_Seine$Date), format="%m/%d/%y")

MCR_Seine <- MCR_Seine %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) #Sets the Month to automatically order via month order [lubridate package]

MCR_Seine$Year <- as.numeric( format(MCR_Seine$Date, format="%Y") )

# reorder and rename columns
MCR_Seine <- MCR_Seine[, c(1, 8 ,7, 2,4 )]
colnames(MCR_Seine)[colnames(MCR_Seine) == "Length..mm."] <- "CW"
MCR_Seine_Sub <- size.class(MCR_Seine, NA, "sub")
```

# MCR daaset Beach Seine [2001-2007]
```{r}
MCR_Pots <- read.csv("../Data/MCR_Pots.csv", stringsAsFactors = FALSE)
# Redefining Dates
MCR_Pots$Date <- as.Date( as.character(MCR_Pots$Date), format="%d-%b-%y")

MCR_Pots <- MCR_Pots %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) #Sets the Month to automatically order via month order [lubridate package]

MCR_Pots$Year <- as.numeric( format(MCR_Pots$Date, format="%Y") )

# reorder and rename columns
MCR_Pots <- MCR_Pots[, c(1, 9, 8, 4, 7 )]
colnames(MCR_Pots)[colnames(MCR_Pots) == "sz"] <- "CW"
MCR_Pots_Sub <- size.class(MCR_Pots, NA, "sub")

```


# August 2021 data 
```{r}
Dcrab_2021 <- read_csv("../Data/Dungeness_Crab_8-31-2021.csv")
Dcrab_2021 <- Dcrab_2021[, 1:3]

# input data not included in sheet by given by Francis on 9/1
Dcrab_2021$Soak.Time <- rep(10, nrow(Dcrab_2021))
Dcrab_2021$Date <- rep("08-31-21", nrow(Dcrab_2021))
Dcrab_2021$Date <-as.Date(Dcrab_2021$Date, format="%m-%d-%y")
Dcrab_2021 <- Dcrab_2021 %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) 
Dcrab_2021$Year <- as.numeric( format(Dcrab_2021$Date, format="%Y") )

# reformat data
Dcrab_2021 <- Dcrab_2021[, c(5:7, 2:3, 1, 4)]
colnames(Dcrab_2021) <- c("Date", "Month", "Year", "CW", "Sex", "Pot","Soak.Time.hr")
Dcrab_2021$Sex <- ifelse(Dcrab_2021$Sex == "M", 1, 2)
Dcrab_2021$CW <- round(Dcrab_2021$CW * 25.4) # was recorded in inches

# reorder the data
index<- with(Dcrab_2021, order(Year, Month, Date, Pot)) #places the order
  Dcrab_2021 <- Dcrab_2021[index,]

# merge with pots_N then run est. mort
Dcrab_14_20_21 <- merge(Pots_N, Dcrab_2021, by=c("Date", "Month","Year","Pot", "CW", "Sex", "Soak.Time.hr"), all=TRUE)
# save(Dcrab_14_20_21, file = "../Data/Dcrab_14.20.21.Rdata")
```


