---
title: "Estimating Mortality"
author: "Montana McLeod"
date: "10/15/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/THESIS/Dungeness_crab/DungenessCrabMortality/Code")
```


```{r warnings=FALSE}
library(ggplot2)
library(Sleuth3)
library(multcomp)
library('patchwork')
library('RColorBrewer')
library(viridis)
library(dplyr)
library(lubridate)
library(wesanderson)
suppressPackageStartupMessages("Done")
```


# Load Manipulated Data
```{r}
source("./Library/total.pots.crabs.R")
source("./Library/total.crabs.per.pot.R")
source("./Library/CPUE.R")
source("./Library/est.mort.CPUE.R")
source("./Library/molt.prob.R")
source("./Library/size.class.R")

load("../Data/Source.D.crab.Rdata")
#data_Molt <- subset(Pots_N,  Month == "April" | Month == "September") #Pre-molt and post-molt
```


# Run functions to get Natural Mortality estimates via CPUE
```{r}
Sub_males <- total.pots.crabs(Pots_N, "sub")
Sub_males <- CPUE(Sub_males)
Total_Mort_CPUE <- est.mort.CPUE(Sub_males, "N")
Est_Mort_CPUE <- est.mort.CPUE(Sub_males, "Y")

#Cond_Pots_N <- total.crabs.per.pot(Pots_N)
```

# Estimate using the molt-in and molt-out proportions 
```{r}
Males <- total.pots.crabs(Pots_N, "total")
Males <- CPUE(Males)
Males <- molt.prob(Males)

#prepare df of survival estiamtes
Est_Mort_InOut <- as.data.frame(rbind(2014,2020))
Est_Mort_InOut$N.mort <- rbind(surv.molt(Males, 2014, 1), surv.molt(Males, 2020, 1))
```





