---
title: "Rarefaction"
author: "Montana McLeod"
date: "8/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/2019-2020/THESIS/Dungeness_crab/Code")
```



```{r warnings=FALSE}
library(ggplot2)
library(Sleuth3)
library(dplyr)
library(multcomp)
library('patchwork')
library('RColorBrewer')
library(viridis)
library(dplyr)
library(lubridate)
library(wesanderson)
```



# Adding data
## Eder grant Data from 2020
```{r}
#Data collected in 2020 (thru September 2020)
NEW_data<-read.csv("./Data/CrabSizes2020.csv" , stringsAsFactors = FALSE)
colnames(NEW_data)<- c("Date","Vessel", "Pot","Lat","Long","Depth", "Box", "BAIT","SEX","Carapace.Width","Shell.Cond","Comments", "LL1", "LL2") #rename to match previous DF for the Merge

#Fix lat errors
NEW_data$Comments <- ifelse(NEW_data$Lat == "Missing!", "Missing!", NEW_data$Comments)
NEW_data$Lat <- ifelse(NEW_data$Lat == "44.36.??", "44.36", 
                       ifelse(NEW_data$Lat == "" | NEW_data$Lat == "Missing!", NA, NEW_data$Lat) )

#Fix long errors
NEW_data$Long <- ifelse(NEW_data$Long == "-124.06.??", "-124.06", 
                        ifelse(NEW_data$Long == "", NA, NEW_data$Long) )

#ADD & Fix dates
NEW_data$Date <- as.Date(NEW_data$Date, format="%m/%d/%y")
NEW_data <- NEW_data %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) #Sets the Month to automatically order via month order [lubridate package]

NEW_data$Soak.Time.hr <- ifelse(NEW_data$Date == "2020-06-10", 8,  24 )

#Fix carapace width errors
NEW_data$Carapace.Width <- as.numeric (ifelse(NEW_data$Carapace.Width == "?" | NEW_data$Carapace.Width == "", NA, NEW_data$Carapace.Width) ) 


NEW_data <- NEW_data[ ,c(1,15,3,9,10,11,16)]
``` 


# Rarefaction FUNCTION
```{r}
crabs.per.pot <- subset(NEW_data, select = Date : Soak.Time.hr) #pulls the two dates in 2020 that have 12 pots each
#rarefy(crabs.per.pot$Pot, 5)
crabs.per.pot.sub.males <- subset(NEW_data, SEX== 1 & Carapace.Width %in% c(140 : 159), select = Date : Soak.Time.hr)

#randomize the sub samples
xyz <- vector(mode = "list", length = 6)
sub_samp <- c(1:4,6) #sample five in july 2020 was lost 
for(i in 1:6){
  xyz[[i]] <- c(sample(sub_samp, i, replace=T), rep(NA, 6-i))
  } #Draws samples to add pots -> results are the pots we will take samples from  


#samp.pots.1 <- sample(c(1:4,6), 1)
rarefaction <- function(data, no, po){
    xyz[[no]] <- c(sample(sub_samp, no, replace=T), rep(NA, po - no))
      #Draws samples to add pots -> results are the pots we will take samples from  
    sub <- subset(data, Pot %in% na.omit(xyz[[no]]) )
           
    # Making a Julian date by the year 
    sub$J.date <- julian.Date(sub$Date, as.Date("2020-01-01"), by= 'Year' )
    
    #When there is a different sample date (i.e. sample), records total pots used and number of crabs collected 
    sub$Total.crabs <- rep(NA, nrow(sub) )
    j=1
    for(i in 2:nrow(sub)){
      if(sub$Date[i] !=  sub$Date[i-1])
      { sub$Total.crabs[j:i] <- (i-j);
      j=i}
    
      if(i == nrow(sub)) {
        sub$Total.crabs[j:i] <- i-j +1
      } }
    
    ## CHANGES the total pots based on fxn
    sub$Total.pots <- rep(no, nrow(sub))
    
    # EFFORT: = soak time * # of traps in a sample string
    sub$Effort <- sub$Soak.Time.hr * sub$Total.pots
    
    # CPUE = # of crabs caught in a string of traps / standard effort
    sub$CPUE <- sub$Total.crabs / sub$Effort
    
    #estimating mortality for samples in same year but different months
    sub$N.Mort <- rep(0, nrow(sub)) #NULL column
    
    #MORTALITY ESTIMATE
    Est<- aggregate(cbind(J.date, Soak.Time.hr, Total.pots,Total.crabs, Effort, CPUE, N.Mort) ~ Date, data = sub, mean) #reports just the individual date and the CPUE
    #Est$Month <- as.numeric( format(Est$Date, format="%m") ) #month
}

```

# Rarefaction of All D. crab
```{r}
# average across itterations of each different pot combo. 
### FOR SOME REASON, THE FXN WILL NOT ALLOW THE FOR LOOP FROM LINE 127-129 IN THE FXN, SPITS OUT AN ERROR. 
##### HAPPY TO HEAR SUGGESTIONS FOR MAKING THIS CHUNK CLEANER IF YOU CAN FIND A WORK AROUND THE FOR LOOP
 #randomize the sub samples

Avg_rare <- data.frame(Pots = c(1:6)) #df for results
n = 500 #no. of iterations 
pots = 6 #no of total pots


for(p in 1:pots){
    for(s in 1:n){
          Est<- rarefaction(crabs.per.pot, p, pots)
            # Equation for natural mortality - only keeps last N. mort. value 
              Est$N.Mort[nrow(Est)] <- (-1/( (Est$J.date[5]) - (Est$J.date[2]) ) )*log(Est$CPUE[5] /  Est$CPUE[2] )  
              
    Avg_rare[p,s+1] <- Est$N.Mort[nrow(Est)] #store itterations in df
    }
  x <- unlist(Avg_rare[p, c(2:(n + 1) )] )
  Avg_rare[p,(n+2)] <- mean(na.omit(x)) #have to unlist b4 calculate the mean of each pot
}
colnames(Avg_rare)[colnames(Avg_rare) == "V502"] <- "Avg"
#Avg_rare$Avg.N.Mort <- rep(0.01189,6) # sub adults


 ggplot(Avg_rare, aes(x=Pots, y=Avg))+
    #geom_smooth(method = lm, se = T)+
    geom_point()+
    #geom_line(data.frame(spline(Avg_rare))) +
    guides(color="legend")+
    ggtitle("Rarefaction") 
```


# Rarefaction of Sub-adult Males
```{r}
n = 50 #no. of iterations 
pots = 6 #no of total pots

for(p in 1:pots){
    for(s in 1:n){
          Est<- rarefaction(crabs.per.pot.sub.males, p, pots)
            # Equation for natural mortality - only keeps last N. mort. value from june to july 2020
            if(nrow(Est) == 1){
                Est$N.Mort <- rep(NA,1) }
            if(nrow(Est) > 1) {   
              for(i in 2: nrow(Est)){
                Est$N.Mort[i] <- (-1/( (Est$J.date[i]) - (Est$J.date[i-1]) ) )*log(Est$CPUE[i] /
                Est$CPUE[i-1] )  
              }
            }
    Avg_rare[p,s+1] <- Est$N.Mort[nrow(Est)] #store itterations in df
    }
  x <- unlist(Avg_rare[p, c(2:(n + 1) )] )
  Avg_rare[p,(n+2)] <- mean(x) #have to unlist b4 calculate the mean of each pot
}
colnames(Avg_rare)[colnames(Avg_rare) == "V52"] <- "Avg"

 ggplot(Avg_rare, aes(x=Pots, y=Avg))+
    geom_smooth(method = lm, se = T)+
    geom_point()+
    #geom_hline(yintercept=0.01189, color= 'red', linetype="dashed")+ #sub adult males
    guides(color="legend")+
    ggtitle("Rarefaction of Sub-adult Males") 

```


# Baseline estimate of N. Mortality of April - August 2020
```{r}
 all <- NEW_data
 sub <- subset(NEW_data, SEX== 1 & Carapace.Width >= 140 & Carapace.Width <= 159)


#randomize the sub samples
xyz <- vector(mode = "list", length = 12)
sub_samp <- c(1:4,12) #sample five in july 2020 was lost 

 #All_12_pots <- function(x){
   All_12_pots <- all
  # Making a Julian date by the year 
  All_12_pots$J.date <- julian.Date(All_12_pots$Date, as.Date("2020-01-01"), by= 'Year' )
  
  #When there is a different sample date (i.e. sample), records total pots used and number of crabs collected 
  All_12_pots$Total.crabs <- rep(NA, nrow(All_12_pots) )
  All_12_pots$Total.pots <- rep(NA, nrow(All_12_pots) )
  j=1
  for(i in 2:nrow(All_12_pots)){
    if(All_12_pots$Date[i] !=  All_12_pots$Date[i-1])
    { All_12_pots$Total.crabs[j:i] <- (i-j);
      All_12_pots$Total.pots[j:i] <- All_12_pots$Pot[i-1];
    j=i}
  
    if(i == nrow(All_12_pots)) {
      All_12_pots$Total.crabs[j:i] <- i-j +1;
      All_12_pots$Total.pots[j:i] <- All_12_pots$Pot[i];
    } }
  
  # EFFORT: = soak time * # of traps in a sample string
  All_12_pots$Effort <- All_12_pots$Soak.Time.hr * All_12_pots$Total.pots
  
  # CPUE = # of crabs caught in a string of traps / standard effort
  All_12_pots$CPUE <- All_12_pots$Total.crabs / All_12_pots$Effort
  
  #estimating mortality for samples in same year but different months
  All_12_pots$N.Mort <- rep(0, nrow(All_12_pots)) #NULL column
  
  #MORTALITY ESTIMATE
  Est_Real<- aggregate(cbind(J.date, Soak.Time.hr, Total.pots,Total.crabs, Effort, CPUE, N.Mort) ~ Date, data = All_12_pots, mean) #reports just the individual date and the CPUE
  #Est_Real$Month <- as.numeric( format(Est_Real$Date, format="%m") ) #month
  
  
  for(i in 2: nrow(Est_Real)){
    Est_Real$N.Mort[i] <- (-1/( (Est_Real$J.date[i]) - (Est_Real$J.date[i-1]) ) )*log(Est_Real$CPUE[i] / Est_Real$CPUE[i-1] )  ## USED the 3rd value because low effort due to short soak time in last sample
    }
 #}
 
#Create dataframes for all crabs and sub males
#Est_Real <- function(all)
  April_July <-  Est_Real$N.Mort[3] #stores value for later use
  April_July_sub <-  Est_Real$N.Mort[3] 
```


# Rarefaction to 12 pots of all crabs
```{r}
#removes the month of June from analysis which only has 6 pots
crabs.per.pot <- subset(crabs.per.pot, Month != "June")

Avg_rare <- data.frame(Pots = c(1:12)) #df for results
n = 500 #no. of iterations 
pots = 12 #no of total pots

for(p in 1:pots){
    for(s in 1:n){
          Est<- rarefaction(crabs.per.pot, p, pots)
            # Equation for natural mortality - only keeps last N. mort. value from june to july 2020
            for(i in 2: nrow(Est)){
              Est$N.Mort[i] <- (-1/( (Est$J.date[i]) - (Est$J.date[i-1]) ) )*log(Est$CPUE[i] /
              Est$CPUE[i-1] )  
              }
    Avg_rare[p,s+1] <- Est$N.Mort[nrow(Est)] #store itterations in df
    }
  x <- unlist(Avg_rare[p, c(2:(n + 1) )] )
  Avg_rare[p,(n+2)] <- mean(x) #have to unlist b4 calculate the mean of each pot
}
colnames(Avg_rare)[colnames(Avg_rare) == "V502"] <- "Avg"


 ggplot(Avg_rare, aes(x=Pots, y=Avg))+
    geom_smooth(method = lm, se = T)+
    geom_point()+
    #geom_hline(yintercept=-0.0051189, color= 'red', linetype="dashed")+ #sub adult males
    #geom_hline(yintercept= April_July, color= 'red', linetype="dashed")+ #adults
    guides(color="legend")+
    ggtitle("Rarefaction 12 Pots") 

```


# Rarefaction to 12 pots of sub-adult crabs
```{r}
#removes the month of June from analysis which only has 6 pots
crabs.per.pot.sub.males <- subset(crabs.per.pot.sub.males, Month != "June")

Avg_rare <- data.frame(Pots = c(1:12)) #df for results
n = 500 #no. of iterations 
pots = 12 #no of total pots

for(p in 1:pots){
    for(s in 1:n){
          Est<- rarefaction(crabs.per.pot, p, pots)
            # Equation for natural mortality - only keeps last N. mort. value from june to july 2020
            if(nrow(Est) == 1){
                Est$N.Mort <- rep(NA,1) }
            if(nrow(Est) > 1) {   
              for(i in 2: nrow(Est)){
                Est$N.Mort[i] <- (-1/( (Est$J.date[i]) - (Est$J.date[i-1]) ) )*log(Est$CPUE[i] /
                Est$CPUE[i-1] )  
              }
            }
    Avg_rare[p,s+1] <- Est$N.Mort[nrow(Est)] #store itterations in df
    }
  x <- unlist(Avg_rare[p, c(2:(n + 1) )] )
  Avg_rare[p,(n+2)] <- mean(x) #have to unlist b4 calculate the mean of each pot
}
colnames(Avg_rare)[colnames(Avg_rare) == "V502"] <- "Avg"


 ggplot(Avg_rare, aes(x=Pots, y=Avg))+
    #geom_smooth(method = lm, se = T)+
    geom_point()+
    geom_line(data.frame(spline(Avg_rare))) +
    #geom_hline(yintercept= April_July_sub, color= 'red', linetype="dashed")+ #sub adult males
    #geom_hline(yintercept= Est_Real$N.Mort[3], color= 'red', linetype="dashed")+ #adults
    guides(color="legend")+
    ggtitle("Rarefaction 12 Pots: sub-adult males") 
```




# if we want to see if number of crabs is affected
```{r}
crabs.per.pot <- subset(Up_data_N,  Year== 2020, select = Date : Soak.Time.hr) #pulls the two dates in 2020 that have 12 pots each
#rarefy(crabs.per.pot$Pot, 5)

xyz <-matrix(0, nrow=6, ncol = 6) #where randomization is stored
sub_samples <- array(rep(NA, 100* 8* 6), c(100,8,6) ) #where we will store the dfs that will calc. n.mort.
set.seed(23)

for(i in 1:6){
  xyz[i,] <- c(sample(1:6, i, replace=T), rep(NA, 6-i))
  #Draws samples to add pots -> results are the pots we will take samples from 
  }

samp.pots.1 <- sample(c(1:4,6), 1)
sub_sample_1 <- subset(crabs.per.pot, Pot == na.omit(xyz[1,])[1])

#When there is a different sample date (i.e. sample), records total pots used and number of crabs collected 
sub_sample_1$Total.crabs <- rep(NA,nrow(sub_sample_1))
j=1
for(i in 2:nrow(sub_sample_1)){
  if(sub_sample_1$Date[i] !=  sub_sample_1$Date[i-1])
  { sub_sample_1$Total.crabs[j:i] <- (i-j);
  j=i}

  if(i == nrow(sub_sample_1)) {
    sub_sample_1$Total.crabs[j:i] <- i-j +1
  } }
sub_sample_1$Total.pots <- rep(1, nrow(sub_sample_1))
x.1 <- aggregate(Total.crabs ~ Total.pots, data = sub_sample_1, mean)

```





